### ISSUE TITLE
Macros with both @static and @instanciated

### ISSUE THREAD

**Issue by kylekatarnls** [KristofMorva/laravel-ide-macros#4]
Hello,

Most macros are callable both statically and dynamically.

A simple example:
```php
<?php

Carbon::macro('getHexadecimalYear', function () {
  return dechex((isset($this) ? $this : static::now())->year);
});

echo Carbon::parse('1998-06-17')->getHexadecimalYear();
echo "\n";
echo Carbon::getHexadecimalYear();
```

`getHexadecimalYear` works well statically (use current date) and on instance (use the instance year).

And in practice, you can't prevent any macro to be called in a way or the other unless you throw an exception from inside the macro.

So I think the right approach is to create 2 files **_ide_static_macros.php** and **_ide_dynamic_macros.php** and put every macro with and without `static` keyword until an explicit annotation such as `@static` / `@instanciated` would be present in the PHPDoc, in this case only the macro would be in only one file.

What do you think of it?

**Comment by CupOfTea696** [comment]
If your method can be called statically, it should just work without needing any annotations.

**Comment by kylekatarnls** [comment]
Of course not, since no `public static function` is created, that's the point.

**Comment by CupOfTea696** [comment]
Just leave out the `@instantiated` tag, your IDE should suggested the method in both static and instantiated context.

**Comment by kylekatarnls** [comment]
No it does not (on PHPStorm or any IDE with a correct autocompletion) and it's perfectly logical considering how it works:

https://github.com/KristofMorva/laravel-ide-macros/blob/ef40cd66dd50e57d6e60e7986aa910984790d143/src/Console/MacrosCommand.php#L102

If `@instantiated` you get `public function` then you can see there is  `continue;` so you don't get `public static function`.

IDE suggest static methods on `Class::` and instanciated methods on `(new Class)->` and this is perfectly correct.

But macros could be both and `laravel-ide-macros` should handle this case as it's pretty common. A working solution is creating 2 files, 1 for static, 1 for instanciated.

**Comment by kylekatarnls** [comment]
Please @KristofMorva have a look on this. If this project is still maintained, I can propose a pull-request.

**Comment by KristofMorva** [comment]
Sorry, for some reason I didn't get a notification until you tagged me. It makes sense, and I'm open to clean PRs. It's sad that we can't define a static and an instanced version of a method even in PHP7 (does it result in an error in PHPStorm?), I wonder if it works if both classes are in the same file?

If we really need 2 files, I think it's better to use the current filename for the instanced class methods, and have a new one only for the static ones, otherwise people would have to manually remove the current file.

**Comment by kylekatarnls** [comment]
> I wonder if it works if both classes are in the same file?

I tried, but as it's not allowed in PHP, PHPStorm marks it as red and suggestions does not work for the second method declared.

> otherwise people would have to manually remove the current file.

I don't get it, `php artisan ide-helper:macros` will rewrite both files.

**Comment by KristofMorva** [comment]
I mean, if the current file is called ide_macros, and now we'd write ide_dynamic_macros and ide_static_macros instead, people would have an unnecessary ide_macros leftover file from the current version of this package.

That's why I propose using the original filename instead of ide_dynamic_macros (and now the additional ide_static_macros, or even ide_macros_static for better alphabetical ordering). I hope it's clear now :)

**Comment by kylekatarnls** [comment]
OK, #7 is here.

**Comment by KristofMorva** [comment]
Let's continue the discussion in #7.
